### ISSUE TITLE
Would you mind adding some info to your wiki regarding compatible USB Bluetooth dongles?

### ISSUE THREAD

**Issue by ovizii** [Arcadia197/rpi-audio-receiver#4]
Would you mind adding some info to your wiki regarding compatible USB Bluetooth dongles? 
I'm busy googling but if you have first-hand experience that would make things a lot easier.

Thank you

**Comment by Arcadia197** [comment]
Hey there!
This probably comes too late for you but here is an answer nonetheless:
I am using the internal Bluetooth and find that the sound is working well. However, I do not deploy any other network heavy services on my system so this might affect the performance.

In general, as long as you are able to select the Bluetooth dongle internally and change it in the Bluetooth audio script it should work

**Comment by ovizii** [comment]
> Hey there! This probably comes too late for you but here is an answer nonetheless: I am using the internal Bluetooth and find that the sound is working well. However, I do not deploy any other network heavy services on my system so this might affect the performance.
> 
> In general, as long as you are able to select the Bluetooth dongle internally and change it in the Bluetooth audio script it should work

Strange reply, as the reason I asked this question is that in your [README](https://github.com/Arcadia197/rpi-audio-receiver/blob/rpi-zero-w/README.md) you said:

> ### Requirements
> A USB Bluetooth dongle (the internal Raspberry Pi Bluetooth chipset turned out as not suited for audio playback and causes all kinds of strange connectivity problems)


which sounds contradictory to me or am I misreading something here?

**Comment by Arcadia197** [comment]
Well spotted! Thanks for pointing this out.

The part in the readme was taken from the original repository and I did not change the line to match my own experience.
This fork is specifically dedicated for zero1w to work with less requirements and from my experience (running 3 systems for almost two years now) the internal Bluetooth is sufficient.

I addressed it and changed it accordingly.

**Comment by ovizii** [comment]
I understand, thanks for explaining. There's another small error, the link to the original repo in your README is: 

Original repository can be found [here](https://github.com/Arcadia197/rpi-audio-receiver/blob/rpi-zero-w/github.com/nicokaiser/rpi-audio-receiver).

The right link would be: https://github.com/nicokaiser/rpi-audio-receiver

btw. did you add snapcast support? It is stated in your README but not in the original one. I assuem you did.

**Comment by Arcadia197** [comment]
> There's another small error,

Thanks, I updated the link (forgot the https:// in front ..)


> btw. did you add snapcast support? It is stated in your README but not in the original one. I assuem you did.

Snapcast support is added and the given script successfully installs Snapcast. However, I experience that the devices are having difficulties managing the traffic and the audio gets corrupted pretty fast. This service might work better with a Bluetooth dongle but I didn't try it out yet.
