### ISSUE TITLE
Bluetooth installation fails on newer Raspberry Pi OS versions on Raspi Zero W

### ISSUE THREAD

**Issue by janek** [Arcadia197/rpi-audio-receiver#5]
On a fresh Raspberry Pi Zero W with `Raspbian GNU/Linux 11 (bullseye)"` I get `: Package 'bluealsa' has no installation candidate`.

Seems like the `bluealsa` package is not available for Bullseye (and probably above). 
Some sources and alternatives in links below:

https://raspberrypi.stackexchange.com/questions/140444/bluealsa-on-pi-zero-can-not-be-installed
https://forums.raspberrypi.com/viewtopic.php?t=344797
https://gist.github.com/actuino/9548329d1bba6663a63886067af5e4cb

**Comment by Arcadia197** [comment]
Thanks for the hint.

As stated in the description, this fork is intended to only work on Raspbian Buster.
It serves as a downgrade to work with Bluealsa, as the chip on the zero1 is not powerful enough to handle Pulseaudio with Bluetooth without corrupting the sound to a noticeable degree.

**Comment by janek** [comment]
Thank you for your explanation, sorry I missed that info!
